/*
 * webAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ToDoApiCli.Api;
using ToDoApiCli.Model;
using ToDoApiCli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ToDoApiCli.Test.Model
{
    /// <summary>
    ///  Class for testing Myitem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MyitemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Myitem
        //private Myitem instance;

        public MyitemTests()
        {
            // TODO uncomment below to create an instance of Myitem
            //instance = new Myitem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Myitem
        /// </summary>
        [Fact]
        public void MyitemInstanceTest()
        {
            // TODO uncomment below to test "IsType" Myitem
            //Assert.IsType<Myitem>(instance);
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'MyitemId'
        /// </summary>
        [Fact]
        public void MyitemIdTest()
        {
            // TODO unit test for the property 'MyitemId'
        }
        /// <summary>
        /// Test the property 'DateToDone'
        /// </summary>
        [Fact]
        public void DateToDoneTest()
        {
            // TODO unit test for the property 'DateToDone'
        }
        /// <summary>
        /// Test the property 'IsDone'
        /// </summary>
        [Fact]
        public void IsDoneTest()
        {
            // TODO unit test for the property 'IsDone'
        }

    }

}
